### ISSUE TITLE
ASS/SSA

### ISSUE THREAD

**Issue by Disinterpreter** [smacke/subsync#11]
Could you make an ASS/SSA support besides SRT?

ASS example and specification: https://www.matroska.org/technical/specs/subtitles/ssa.html

**Comment by pannal** [comment]
This is pretty easy to achieve using [PySubs2](https://github.com/tkarabela/pysubs2). When used as a library, not via CLI, PySubs parses subtitle files and normalizes them to a generic Subtitle object with iterable entries and a bunch of tools for alignment and modification.

I use it with Sub-Zero, it supports multiple input and output formats.

**Comment by 54** [comment]
ASS subs would definitely be a huge improvement. For anime, because of the crazy typesetting the fansub community does, it is basically the standard.

**Comment by smacke** [comment]
@54 I've implemented this functionality in master but it's currently untested on real data. Will bump version and STABLE pointers once I do so.

**Comment by smacke** [comment]
Still haven't tested yet but I promise I will soon! I went ahead and bumped the version number because the SSA/ASS functionality shouldn't interact badly with existing SRT functionality. As such, please feel welcome to trial, and I would love to know if it works (though either way I will make sure to properly test soon). Upgrading can be done via the following command:
`pip install --upgrade git+https://github.com/smacke/subsync@STABLE`

**Comment by smacke** [comment]
Turns out there was a bug (this is why we test); I've added test cases and everything should be fixed now:
`pip install --upgrade git+https://github.com/smacke/subsync@STABLE`

**Comment by 54** [comment]
Beautiful, thanks!
