### ISSUE TITLE
Allow for SRT extraction from MKV directly instead of using VAD for synchronization

### ISSUE THREAD

**Issue by Disinterpreter** [smacke/subsync#15]
Extraction SRT (same for ASS of course) from MKV container in time of running subsync (without arguments with external .srt file)

https://mkvtoolnix.download/doc/mkvextract.html

**Comment by Sec-ant** [comment]
![image](https://user-images.githubusercontent.com/10386119/63577371-cf128180-c5c0-11e9-99b5-e2862b8c399a.png)
I am a Python new comer, but this repo is what I have been dreaming of so I took some time and wrote a snippet for SRT extraction (without parsing by python srt lib, just the text) and the result seems good. SRT extraction costs much little time compared to audio extraction (see figure above). However there are some tricky things:
- The progress bar position of tqdm is acquired by parsing the ffmpeg stderr log redirected by PIPE with `-loglevel` option being `info` (default) because there seems no way to acquire the full size of the subrip stream.
- The specific subrip stream is selected according to the first audio track's language and the size (`NUM_OF_BYTES_eng`) of the subrip stream (There are cases where the first text-format sub contains only few foreign language translation). I'd love to add an interactive option for user to select.
- I hope this feature can be joined with the ASS/SSA support feature and make subsync a more powerful tool~

**Comment by smacke** [comment]
@Sec-ant, my apologies for leaving you hanging for so long. This type of functionality would be really cool to have in terms of speed -- if it's possible to get the voice segments directly from subtitles in the mkv instead of from audio extraction, this should be the default in my opinion.

Thank you for taking the time to dig into this. Would you be willing to submit a pull request with whatever you have? No need to spend a lot of time on fully integrating or making it perfect, but it serve as a great starting point for understanding what needs to be done, and I'd be happy to provide suggestions or changes while making sure you get credit for the PR.

**Comment by smacke** [comment]
Great news! The latest V incorporates this functionality now.
```
pip install --upgrade git+https://github.com/smacke/subsync@stable
```
