### ISSUE TITLE
Unnecessary requirement?

### ISSUE THREAD

**Issue by g-mc** [smacke/subsync#17]
https://github.com/smacke/subsync/blob/7cb85e78efc0bac9628cbb81609f93978aeb631e/requirements.txt#L1

**Comment by smacke** [comment]
You're right; it's not necessary for the supported python v's (2.7, 3.4, 3.5, 3.6, 3.7) as `argparse` is in the standard library for these. I haven't tested on other pythons, but I'm going to leave it in the requirements since it can't hurt anything on the off chance that someone is still on e.g. 2.6.
