### ISSUE TITLE
Synchronization from a reference.srt did not work well for me.

### ISSUE THREAD

**Issue by acamposxp** [smacke/subsync#28]
subsync reference.srt -i unsynchronized.srt -o synchronized.srt

**reference.srt**

1
00:03:02,809 --> 00:03:04,686
Brichet, court today.

2
00:03:13,945 --> 00:03:17,365
Her and her damned doors!

3
00:03:30,378 --> 00:03:32,171
Marceau, court today.

**unsynchronized.srt**

1
00:03:03,000 --> 00:03:04,911
Brichet! O Tribunal de Justiça!

2
00:03:13,760 --> 00:03:17,025
Ela e suas malditas portas!

3
00:03:29,439 --> 00:03:31,350
Marceau! O Tribunal de Justiça!

**synchronized.srt**

1
00:07:33,770 --> 00:07:35,680
Brichet! O Tribunal de Justiça!

2
00:07:44,530 --> 00:07:47,790
Ela e suas malditas portas!

3
00:08:00,200 --> 00:08:02,120
Marceau! O Tribunal de Justiça!

**Comment by smacke** [comment]
Hi there, would you be willing to provide these files as test cases? I am guessing there is something subtle going on specific to them.

**Comment by acamposxp** [comment]
@smacke, [https://drive.google.com/uc?id=1slDRVjGqv_e8gQS6FO5YvINLMN-yPXcv](url)

**Comment by acamposxp** [comment]
Curious is that the same thing happens when the synchronization is done between subtitle and audio.

**Comment by smacke** [comment]
Hi @acamposxp, it looks like the English and Portuguese for this movie differ pretty significantly. Unfortunately subsync isn't really equipped right now for synchronization beyond a fixed offset (although this is in the works).

It seems as though either the Portuguese subtitles are not very high quality, or they correspond to a different cut of the movie -- it's not really possible to align them to the audio using a fixed offset, while the English corresponds pretty directly with the audio (this is why you see the same offset whether you use the audio or the English srt).

For example, they start off at roughly the same spot, but the English places "We'll suffocate in here" at 4:14, while the Portuguese places "Estamos sufocando aqui" at 4:08. The English generally appears later than the Portuguese, but not in any kind of correlated way, which is what subsync needs. Although correcting a fixed starting offset seems to help synchronize the majority of subtitles, it's definitely a limitation that I've been thinking about addressing.

I'll leave this open as this ticket contains what looks like a pretty useful test case as we transition to synchronization beyond a fixed subset.

**Comment by smacke** [comment]
Hi @acamposxp, with the frame rate scaling improvements in the latest release, it looks like your subs are now synced properly (see end of this post). Thank you for providing the test case -- it's thanks to contributions like yours that I can make further improvements to this software.

I know it's been quite a long time since you initially opened this issue, but I hope you'll consider this project the next time you encounter -- there are now quite a number of improvements in the latest version. You can grab it with:

`pip install --upgrade git+https://github.com/smacke/subsync@STABLE`

------------------------------------------------------------

**reference.srt**

1
00:03:02,809 --> 00:03:04,686
Brichet, court today.

2
00:03:13,945 --> 00:03:17,365
Her and her damned doors!

3
00:03:30,378 --> 00:03:32,171
Marceau, court today.


**synchronized.srt**

1
00:03:02,807 --> 00:03:04,800
Brichet! O Tribunal de Justiça!

2
00:03:14,027 --> 00:03:17,431
Ela e suas malditas portas!

3
00:03:30,375 --> 00:03:32,368
Marceau! O Tribunal de Justiça!
