### ISSUE TITLE
Installation fails on dependency tensorflow?

### ISSUE THREAD

**Issue by rlue** [smacke/subsync#35]
I'm not too familiar with the python ecosystem, so forgive me if I'm missing something obvious.

I'm trying to install subsync system-wide, and getting the following error:

```sh
$ sudo pip3 install subsync
Collecting subsync
...
Collecting tensorflow==1.5.1 (from subsync)
  ERROR: Could not find a version that satisfies the requirement tensorflow==1.5.1 (from subsync) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.14.0rc0, 1.14.0rc1, 2.0.0a0, 2.0.0b0)
ERROR: No matching distribution found for tensorflow==1.5.1 (from subsync)
```

Obviously [tensorflow 1.5.1 exists in the pypi repos](https://pypi.org/project/tensorflow/1.5.1/); I don't know if this is a python2 vs python3 issue, but manually installing 1.5.1 fails with the same error.

Is there maybe something wrong with the way I have pip configured? Is it a viable option to upgrade the version of tensorflow that subsync depends on?

**Comment by smacke** [comment]
Hi there! Thanks for filling an issue.

So I had to squint for a bit to figure out what was going on, because this tool shouldn't have a tensorflow dependency. It turns out that there is a name collision -- there is this `subsync` which is not yet available in the pypi repos (I'll have to figure out a new name -- see also #36), and there is someone else who already got there first with a similar tool (I haven't checked it out yet, so if you get it working please let me know how it does!)

If you try the following line instead:

`pip3 install git+https://github.com/smacke/subsync`

It should install without a hitch -- please let me know how it works for you!

**Comment by rlue** [comment]
🤦 I'll see myself out now.

(Thanks btw!)
